// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynoenobxrkcagroetqsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlub2Vub2J4cmtjYWdyb2V0cXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDIzNDAsImV4cCI6MjA3MTE3ODM0MH0.5OcHSTvpApPhtHqe6dyHjZV-u0C27so2DPSXe8tlPG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});